server {
    listen 80;
    listen [::]:80;
    server_name agent.jaytipargal.tech;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name agent.jaytipargal.tech;

    ssl_certificate /etc/letsencrypt/live/agent.jaytipargal.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/agent.jaytipargal.tech/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    include snippets/eka-agent-locations.conf;
}
